language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.4
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then mkdir -p build/logs; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so -dxdebug.max_nesting_level=1000 -dmemory_limit=512M ./vendor/bin/kahlan --coverage-text --clover=./build/logs/clover.xml; else ./vendor/bin/kahlan; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
